version: '3.8'

services:
  dvd-bounce:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        VCS_REF: ${VCS_REF:-$(git rev-parse --short HEAD)}
    container_name: dvd-bounce-secure

    # Security: Run as non-root user
    user: "65532:65532"

    # Security: Read-only root filesystem
    read_only: true

    # Security: Remove unnecessary capabilities
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

    # Security: No new privileges
    security_opt:
      - no-new-privileges:true

    # Security: Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

    # Security: Temporary filesystem for writable areas
    tmpfs:
      - /tmp:noexec,nosuid,size=10m
      - /var/run:noexec,nosuid,size=10m

    ports:
      - "8080:80"
      # Temporarily removed HTTPS port
      # - "8443:443"

    volumes:
      - caddy_data:/data
      - caddy_logs:/var/log/caddy

    environment:
      - TZ=UTC
      - CADDY_ADMIN=off

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Restart policy
    restart: unless-stopped

    # Security: Network mode
    networks:
      - dvd_network

networks:
  dvd_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"

volumes:
  caddy_data:
    driver: local
  caddy_logs:
    driver: local