name: Build & Publish Docker

on:
  release:
    types: [published]

jobs:
  docker:
    if: ${{ !github.event.release.prerelease }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version
        id: version
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dvd-bounce:latest -f docker/Dockerfile .

      - name: Tag with version and push all
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/dvd-bounce:latest ${{ secrets.DOCKER_USERNAME }}/dvd-bounce:${{ steps.version.outputs.TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/dvd-bounce:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/dvd-bounce:${{ steps.version.outputs.TAG }}
