name: Build & Publish Docker

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dvd-bounce -f docker/Dockerfile .

      - name: Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dvd-bounce
